### ISSUE TITLE
slic3r Mini PLA Profile Bed Temp

### ISSUE THREAD

**Issue by scott113341** [alephobjects/print_profiles#5]
Hello, the other day I downloaded this profile for printing: https://github.com/alephobjects/print_profiles/blob/master/slic3r/Mini/PLA_medium_mini_slic3r.ini

However, the `start_gcode` needs to be changed, particularly this line:

`M140 S110; get bed temping up during first layer`

110 degrees is way too hot for PLA!  I tried to print twice, but had catastrophic bed adhesion issues.  In the quick start guide, 65 degrees is recommended.  

Thanks for the profile!  Other than that, it worked like a charm.

**Comment by brentmac** [comment]
Profile updated, thanks for catching that!
